version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-db
    environment:
      POSTGRES_DB: medusastore
      POSTGRES_USER: medusauser
      POSTGRES_PASSWORD: pass123
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data  # Adjust the host path for data persistence
